---
- name: running system_mount tasks
  include_tasks: system_mount.yml
  loop: "{{ system_mount | dict2items }}"
  loop_control:
    label: "{{ system_mount_item['key'] }}"
    loop_var: system_mount_item
  when:
    system_mount is defined
